[package]
name = "gradle-dependency-health-checker"
version = "0.1.0"
edition = "2024"

[dependencies]
regex = "1.10"
walkdir = "2.5"
clap = { version = "4.5", features = ["derive"] }
colored = "2.1"
toml = "0.8"
serde = { version = "1.0", features = ["derive"] }
